stages:
  - test
  - build
  - deploy

# Test stage to check Python code quality (you can use a linter or run tests here)
test:
  stage: test
  image: python:3.13
  script:
    - pip install -r requirements.txt
    - pytest tests 

# Build stage to create a Docker image
build:
  stage: build
  image: docker:24
  services:
    - docker:dind
  script:
    - docker build -t group1csci4830:latest .
    - docker tag group1csci4830:latest $DOCKER_HUB_USERNAME/group1csci4830:latest
    - docker save group1csci4830:latest > image.tar  # Save the image to a tar file
  artifacts:
    paths:
      - image.tar  # This will store the image as an artifact
    expire_in: 1 hour  # You can adjust this as needed
  only:
    - main  # Build only on pushes to the main branch

#Deploy stage (optional if you want to push the Docker image)
deploy:
 stage: deploy
 image: docker:24
 services:
   - docker:dind
 script:
   - docker login -u $CI_REGISTRY_USER --password--stdin $CI_REGISTRY_PASSWORD $CI_REGISTRY
   - docker load -i image.tar  # Load the image from the artifact
   - docker push $DOCKER_HUB_USERNAME/group1csci4830:latest
 only:
   - main