stages:
  - test
  - build
  - deploy

# Test stage to check Python code quality (you can use a linter or run tests here)
test:
  stage: test
  image: python:3.13
  script:
    - pip install -r requirements.txt
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - pytest tests 

# Build stage to create a Docker image
build:
  stage: build
  image: docker:24
  services:
    - docker:dind
  script:
    - docker build -t group1csci4830:latest .
    - docker tag group1csci4830:latest $DOCKER_HUB_USERNAME/group1csci4830:latest
    - docker save -o image.tar group1csci4830:latest  
  artifacts:
    paths:
      - image.tar  
  only:
    - main 

#Deploy stage 
deploy:
 stage: deploy
 image: docker:24
 services:
   - docker:dind
 script:
   - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
   - docker load -i image.tar  
   - docker tag group1csci4830:latest $DOCKER_HUB_USERNAME/group1csci4830:latest  
   - docker push $DOCKER_HUB_USERNAME/group1csci4830:latest
 only:
   - main